# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - ./myscript.sh
      - rm bin/*
      - go build -o bin/go-shell main.go
      - bin/go-shell
  
  testbuild:
    cmds:
      - |
        if [[ ! -e bin ]]; then
          echo "No existing bin directory. Making it now."
          mkdir bin
        else
          echo "bin directory exists; proceeding to next step in task."
        fi
        if [[ -f bin/go-shell ]]; then
          rm bin/go-shell
        fi
      - go build -o bin/go-shell main.go
      - bin/go-shell