# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  CREATE_BIN_DIR: No existing bin directory. Making it now.
  BIN_DIR_EXISTS: bin directory exists; proceeding to next step in task.
  DELETE_BINARY: removing existing binary.
  BUILD: building go-shell in bin/ from main.go
  EXECUTE: "executing go-shell"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  build:
    cmds:
      - |
        if [[ ! -e bin ]]; then
          echo "{{.CREATE_BIN_DIR}}"
          mkdir bin
        else
          echo "{{.BIN_DIR_EXISTS}}"
        fi
        if [[ -f bin/go-shell ]]; then
          echo "{{.DELETE_BINARY}}"
          rm bin/go-shell
        fi
      - |
        echo "{{.BUILD}}"
        go build -o bin/go-shell main.go
      - | 
        echo "{{.EXECUTE}}"
        bin/go-shell
    silent: true