# https://taskfile.dev

version: '3'

vars:
  DIR_BIN: bin
  DIR_SRC: src
  EXEC_NAME: go-shell

  MSG_CREATE_BIN_DIR: No existing {{.DIR_BIN}} directory. Making it now...
  MSG_DELETE_BINARY: Removing existing binary...
  MSG_BUILD: Building {{.EXEC_NAME}} in {{.DIR_BIN}}/ from .go files in {{.DIR_SRC}}/...

tasks:
  build:
    desc: builds {{.EXEC_NAME}}
    cmds:
      - |
        if [[ ! -e {{.DIR_BIN}} ]]; then
          echo "{{.MSG_CREATE_BIN_DIR}}"
          mkdir {{.DIR_BIN}}
        fi
        if [[ -f {{.DIR_BIN}}/{{.EXEC_NAME}} ]]; then
          echo "{{.MSG_DELETE_BINARY}}"
          rm {{.DIR_BIN}}/{{.EXEC_NAME}}
        fi
      - |
        echo "{{.MSG_BUILD}}"
        go build \
          -o \
          {{.DIR_BIN}}/{{.EXEC_NAME}} \
          {{.DIR_SRC}}/*.go
    env:
    silent: true

  run:
    desc: runs {{.EXEC_NAME}}
    cmds:
      - |
        {{.DIR_BIN}}/{{.EXEC_NAME}}
    silent: true

  default:
    desc: builds and runs {{.EXEC_NAME}}
    cmds:
      - task: build
      - task: run
    env:
    silent: true

